# 02.   numpy indexing and selection

In [1]:
import numpy as np

In [2]:
arr=np.arange(0,110,10)

In [3]:
arr

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

* **to find array element by location**

In [4]:
arr[8]

80

* **to print array range based on start and end point** 

In [5]:
arr[2:5]   # last element will not considred 

array([20, 30, 40])

In [6]:
arr[0:5]

array([ 0, 10, 20, 30, 40])

* **if we not type start or end value then it will consider start or end point**

In [7]:
arr[5:]   #end value not specify 

array([ 50,  60,  70,  80,  90, 100])

In [8]:
arr[:4]  #Start value is not specify 

array([ 0, 10, 20, 30])

In [9]:
arr[:]  #both value are not specuify

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [10]:
arr[0:5]

array([ 0, 10, 20, 30, 40])

* **brodcast or repalce vlaue of array**

In [23]:
arr[0:5]=100

In [24]:
arr

array([100, 100, 100, 100, 100,  50,  60,  70,  80,  90, 100])

In [28]:
arr=np.arange(0,110,10)

In [29]:
arr

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [30]:
slice_of_arr=arr[:6]

In [31]:
slice_of_arr

array([ 0, 10, 20, 30, 40, 50])

In [34]:
slice_of_arr[:] = 99

In [35]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

* **Here data is not copied to slice_of_arr but it just view to original array**

**numpy do this to avoid memory issue**

In [36]:
arr

array([ 99,  99,  99,  99,  99,  99,  60,  70,  80,  90, 100])

In [37]:
id(slice_of_arr)

2238651433328

In [38]:
id(arr)

2238651434048

In [39]:
id(arr[:6])

2238651457744

#### to Copy the array in to another variable use methond **copy()**

In [46]:
arr_copy=arr   # To copy arr  in arr_copy withount copy methond, it will view original 

In [47]:
arr_copy

array([ 99,  10,  10,  10,  10,  99,  60,  70,  80,  90, 100])

In [48]:
arr_copy[1:5]=10

In [49]:
arr_copy

array([ 99,  10,  10,  10,  10,  99,  60,  70,  80,  90, 100])

In [50]:
arr

array([ 99,  10,  10,  10,  10,  99,  60,  70,  80,  90, 100])

* use method copy

In [51]:
arr_copy=arr.copy()   # To copy arr  in arr_copy

In [52]:
arr_copy

array([ 99,  10,  10,  10,  10,  99,  60,  70,  80,  90, 100])

In [54]:
arr_copy[1:3]=8   # change Paramter of copied arry

In [55]:
arr_copy

array([ 99,   8,   8,  10,  10,  99,  60,  70,  80,  90, 100])

In [56]:
arr   # No change in original 

array([ 99,  10,  10,  10,  10,  99,  60,  70,  80,  90, 100])

# 2 D array 

In [57]:
import numpy as np

In [58]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [59]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [68]:
arr_2d[0]

array([ 5, 10, 15])

In [69]:
arr_2d[0][0]

5

In [70]:
arr_2d[1][1]

25

* **insted of double bracket we can use comma**

In [72]:
arr_2d[1,1]  #

25

In [73]:
arr_2d[1,2]

30

* **to get multiple element from array use slce notion**

In [81]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [82]:
arr_2d[:2,:2]

array([[ 5, 10],
       [20, 25]])

In [83]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [84]:
arr_2d[:2,1:3]

array([[10, 15],
       [25, 30]])

In [85]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

# conditional selection 

In [89]:
arr=np.arange(0,110,10)

In [90]:
arr

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [91]:
arr > 50

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [92]:
bool_arr=arr > 50

In [93]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [94]:
arr[bool_arr]

array([ 60,  70,  80,  90, 100])

In [95]:
arr[arr > 50]

array([ 60,  70,  80,  90, 100])

In [96]:
arr[arr<40]

array([ 0, 10, 20, 30])

* 2D array

In [35]:
arr_2d=np.arange(50).reshape(5,10)

In [36]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [39]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])