# NumPy Operations   
* **Array with Array** 
* **Array with Scalars** 
* **Universal Array Functions** 

In [1]:
import numpy as np

In [2]:
arr=np.arange(0,110,10)

In [3]:
arr

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

* ## Array with Array

In [4]:
arr

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [5]:
arr + arr

array([  0,  20,  40,  60,  80, 100, 120, 140, 160, 180, 200])

In [6]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
arr*arr

array([    0,   100,   400,   900,  1600,  2500,  3600,  4900,  6400,
        8100, 10000])

* **Array with Scalars** 
**Single number broadcast every element in array**

In [22]:
arr

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [23]:
arr+2

array([  2,  12,  22,  32,  42,  52,  62,  72,  82,  92, 102])

In [24]:
arr*2

array([  0,  20,  40,  60,  80, 100, 120, 140, 160, 180, 200])

In [25]:
arr -2

array([-2,  8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [26]:
arr / 2 

array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

##### for 0/0 is not returing any error but it return warning 

In [32]:
1/0

ZeroDivisionError: division by zero

* ###### for 0/0 is not returing any error but it return warning but it return warning with  NAN variable

In [33]:
arr/arr   # for 0/0 is not returing any error but it return warning but it return warning with  NAN variable

C:\Users\sujitd\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

* ###### for 1/0 is not returing any error but it return warning with  INFINITY variable

In [34]:
1/arr   # for 1/0 is not returing any error but it return warning with  INFINITY variable

C:\Users\sujitd\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 0.1       , 0.05      , 0.03333333, 0.025     ,
       0.02      , 0.01666667, 0.01428571, 0.0125    , 0.01111111,
       0.01      ])

In [35]:
arr

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [36]:
arr ** 2   # Square

array([    0,   100,   400,   900,  1600,  2500,  3600,  4900,  6400,
        8100, 10000], dtype=int32)

In [37]:
arr1=arr ** 2 

In [38]:
arr1

array([    0,   100,   400,   900,  1600,  2500,  3600,  4900,  6400,
        8100, 10000], dtype=int32)

# Universal Array Functions

* https://docs.scipy.org/doc/numpy/reference/ufuncs.html

In [51]:
np.sqrt(arr1)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [52]:
arr

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [53]:
np.max(arr)

100

In [54]:
arr.max()

100

In [55]:
np.min(arr)

0

In [56]:
arr.min()

0

In [57]:
np.exp(arr)

array([1.00000000e+00, 2.20264658e+04, 4.85165195e+08, 1.06864746e+13,
       2.35385267e+17, 5.18470553e+21, 1.14200739e+26, 2.51543867e+30,
       5.54062238e+34, 1.22040329e+39, 2.68811714e+43])

In [58]:
np.log(arr)   # logarithamatics

C:\Users\sujitd\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 2.30258509, 2.99573227, 3.40119738, 3.68887945,
       3.91202301, 4.09434456, 4.24849524, 4.38202663, 4.49980967,
       4.60517019])

In [59]:
np.sin(arr)   #Trigonometric sin

array([ 0.        , -0.54402111,  0.91294525, -0.98803162,  0.74511316,
       -0.26237485, -0.30481062,  0.77389068, -0.99388865,  0.89399666,
       -0.50636564])

In [60]:
np.cos(arr)   #Trigonometric cos

array([ 1.        , -0.83907153,  0.40808206,  0.15425145, -0.66693806,
        0.96496603, -0.95241298,  0.6333192 , -0.11038724, -0.44807362,
        0.86231887])

In [50]:
np.cos(0)

1.0